// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flzbofgzosvfnrckmhbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsemJvZmd6b3N2Zm5yY2ttaGJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjM4MzAsImV4cCI6MjA2NDczOTgzMH0.n1SOILYyv4tE0XVcrwxYuiTaUzHzP_TD3zIWwtzq4g8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);